### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by Fratepietro87** [ThyWoof/SolastaUnofficialTranslations#2]
hi 
attached a slightly corrected version of the Italian translation, if you authorize me to push this file on the repository I keep it updated as I find points to improve and / or correct
[Translation-it.zip](https://github.com/ThyWoof/SolastaUnofficialTranslations/files/6292834/Translation-it.zip)

**Comment by ThyWoof** [comment]
Added you to repo as a contributor. Please only push IT json... Update Nexus with your translations.

**Comment by Fratepietro87** [comment]
hi ThyWoof,
 I tried to upload the file but it still tells me that I am not enabled
![image](https://user-images.githubusercontent.com/82342977/114401507-45ebfc00-9ba3-11eb-8ad4-b50a5c7c2921.png)
