### ISSUE TITLE
New Corrections-es

### ISSUE THREAD

**Issue by eku2703** [ThyWoof/SolastaUnofficialTranslations#3]
Hello!
First, thanks for the mod.
Enclose you will find my corrections-es (Spanish) with some basic fixes in translation (UI, Armours, Menu).
Understand that is possible fix the translation directly in Translations-es folder (txt files)... the new corrections is a great idea but (at least in spanish language) corrections are applied to all terms is a big issue!

[Corrections-es.txt](https://github.com/ThyWoof/SolastaUnofficialTranslations/files/6565373/Corrections-es.txt)

Thanks a lot

**Comment by ThyWoof** [comment]
Eduardo - Tienes toda la razon! I don't believe the original game terms will change much in future updates. If you prefer feel free to fork this Repo, apply the changes directly to the Translations-es folder, and I'll merge them.

Gracias Amigo!
