### ISSUE TITLE
Change encoding or font ?

### ISSUE THREAD

**Issue by zaa495** [ThyWoof/SolastaUnofficialTranslations#4]
Hello,
Thanks a lot for your work.
I made a translation into Russian according to the instructions, but in the game there are squares instead of letters.
I think that the font is original, it does not understand Russian symbols.
If it's not difficult, you can help me with the creation of the font, or maybe the settings. I'm unfortunately a beginner and don't know Unity.
I would really appreciate your help. Thanks in advance :-)
Here is the translation into Russian https://drive.google.com/file/d/125_T-aaJAvBnJqI125CLecJxclsqK57P/view?usp=sharing

**Comment by zaa495** [comment]
I have inserted a link to the Russian translation https://drive.google.com/file/d/125_T-aaJAvBnJqI125CLecJxclsqK57P/view?usp=sharing
Need help understanding Russian font 0400-04FF
Saw the article https://forum.unity.com/threads/the-russian-letters-arent-shown-instead-of-them-blocks-help-please.468481/
But there is not enough knowledge to handle: - (((

**Comment by ThyWoof** [comment]
I’m trying the same link to create a new Atlas but I only have time in the weekends

**Comment by zaa495** [comment]
Super, thanks for the answer. Thank you so much for helping.

**Comment by zaa495** [comment]
I almost forgot. If using https://github.com/bbepis/XUnity.AutoTranslator
there you can use the arialuni_sdf_u2019 font for substitution, the OverrideFontTextMeshPro = arialuni_sdf_u2019 parameter and the Cyrillic alphabet in the game is displayed normally. Here is the link to the fonts
https://github.com/bbepis/XUnity.AutoTranslator/releases/download/v4.16.1/TMP_Font_AssetBundles.zip
Maybe this will help in your work.

**Comment by zaa495** [comment]
Hi, Any news ? Did you manage to make the font and atlas?

**Comment by zaa495** [comment]
As I understand it, these fonts are used in the game:

Assistant-Bold SDF Atlas
Assistant-Regular SDF Atlas
Assistant-SemiBold SDF Atlas

Inter-ExtraBold SDF Atlas

LiberationSans SDF Atlas

Noto-Bold SDF Atlas
Noto-Regular SDF Atlas
Noto-Thin SDF Atlas

SourceSansPro-Bold SDF2 Atlas
SourceSansPro-It SDF Atlas
SourceSansPro-Regular SDF2 Atlas

Spectral-Italic SDF Atlas
Spectral-Regular SDF Atlas
SpectralSC-Bold SDF Atlas
Spectral-SemiBoldItalic SDF Atlas

I think the font SourceSansPro - general. Here are the fonts 
https://drive.google.com/file/d/1Y4gNrHY2ZheJQGdfLoc_soHjPRbTRzrD/view?usp=sharing
and Spectral Cyrillic font here
https://drive.google.com/file/d/1M-FRIDS3joaCf07WvwZj09LAT3xMqMol/view?usp=sharing

**Comment by ThyWoof** [comment]
It looks like Russian and Brazilian will be officially supported in an upcoming release... Will stop researching this...
